"""Interview-agent proctoring reactions — verbatim TTS, mic lock, escalation."""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from typing import Any

from livekit import rtc
from livekit.agents import AgentSession

from app.config import Settings

logger = logging.getLogger(__name__)

# Fixed warning scripts — NOT generated by LLM.
_WARNINGS: dict[str, dict[str, dict[int, str]]] = {
    "en": {
        "tab_switch": {
            1: "Please return to the interview window. This session is monitored.",
            2: "Warning: you have left the interview window again. Stay on this tab.",
            3: "Final warning: leaving the interview window is not allowed. This session will end if it happens again.",
        },
        "gaze_away": {
            1: "Please keep your eyes on the screen and stay facing the camera.",
            2: "Warning: you looked away from the screen again. Interviewers can see this.",
            3: "Final warning: keep your attention on the interview. Continued violations will end this session.",
        },
        "multiple_faces": {
            1: "Only you should be visible on camera. Please ask others to leave the frame.",
            2: "Warning: another person is still visible. This is not allowed during the interview.",
            3: "Final warning: multiple people on camera will end this interview.",
        },
        "phone_detected": {
            1: "Please put your phone away and keep it out of the camera view.",
            2: "Warning: a phone is still visible. Remove it from the frame immediately.",
            3: "Final warning: phones are not allowed. The session will end if this continues.",
        },
        "secondary_monitor": {
            1: "An external display is connected. Please disconnect it or use only this screen.",
            2: "Warning: an external monitor is still connected. Use a single display for this interview.",
            3: "Final warning: external displays are not allowed. The session will end if this continues.",
        },
        "default": {
            1: "A proctoring rule was violated. Please follow the interview guidelines.",
            2: "Warning: repeated proctoring violations were detected.",
            3: "Final warning: one more violation will end this interview.",
        },
    },
    "vi": {
        "tab_switch": {
            1: "Vui lòng quay lại cửa sổ phỏng vấn. Phiên này đang được giám sát.",
            2: "Cảnh báo: bạn đã rời cửa sổ phỏng vấn lần nữa. Hãy ở lại tab này.",
            3: "Cảnh báo cuối: không được rời cửa sổ phỏng vấn. Vi phạm tiếp sẽ kết thúc buổi phỏng vấn.",
        },
        "gaze_away": {
            1: "Vui lòng nhìn vào màn hình và giữ mặt hướng về camera.",
            2: "Cảnh báo: bạn lại nhìn ra ngoài màn hình. Hệ thống có ghi nhận.",
            3: "Cảnh báo cuối: hãy tập trung vào buổi phỏng vấn. Vi phạm tiếp sẽ kết thúc phiên.",
        },
        "multiple_faces": {
            1: "Chỉ bạn được xuất hiện trong khung hình. Vui lòng nhờ người khác rời khỏi camera.",
            2: "Cảnh báo: vẫn còn người thứ hai trong khung hình. Điều này không được phép.",
            3: "Cảnh báo cuối: nhiều người trong khung hình sẽ kết thúc buổi phỏng vấn.",
        },
        "phone_detected": {
            1: "Vui lòng cất điện thoại và không để trong khung camera.",
            2: "Cảnh báo: điện thoại vẫn còn trong khung hình. Hãy đưa ra khỏi camera ngay.",
            3: "Cảnh báo cuối: không được dùng điện thoại. Vi phạm tiếp sẽ kết thúc phiên.",
        },
        "secondary_monitor": {
            1: "Phát hiện màn hình phụ. Vui lòng ngắt kết nối hoặc chỉ dùng một màn hình.",
            2: "Cảnh báo: màn hình phụ vẫn đang kết nối. Chỉ dùng một màn hình cho buổi phỏng vấn.",
            3: "Cảnh báo cuối: không được dùng màn hình phụ. Vi phạm tiếp sẽ kết thúc phiên.",
        },
        "default": {
            1: "Đã phát hiện vi phạm quy định. Vui lòng tuân thủ hướng dẫn phỏng vấn.",
            2: "Cảnh báo: vi phạm giám sát lặp lại.",
            3: "Cảnh báo cuối: thêm một vi phạm nữa sẽ kết thúc buổi phỏng vấn.",
        },
    },
}

_ENDING_SCRIPT = {
    "en": "This interview is ending now due to repeated proctoring violations. Thank you for your time.",
    "vi": "Buổi phỏng vấn kết thúc do vi phạm giám sát lặp lại. Cảm ơn bạn.",
}


def _lang_key(language: str) -> str:
    return "vi" if language.lower().startswith("vi") else "en"


def warning_text(*, language: str, kind: str, tier: int) -> str:
    lang = _lang_key(language)
    table = _WARNINGS[lang]
    messages = table.get(kind) or table["default"]
    return messages.get(tier, messages[3])


def escalation_tier(violation_count: int) -> int:
    if violation_count <= 2:
        return 1
    if violation_count <= 4:
        return 2
    return 3


class ProctoringHandler:
    """Listens for proctor:violation data messages and responds with mic lock + TTS."""

    def __init__(
        self,
        *,
        interview_id: str,
        language: str,
        settings: Settings,
        agent_session: AgentSession,
        end_callback: Any,
    ) -> None:
        self._interview_id = interview_id
        self._language = language
        self._settings = settings
        self._agent_session = agent_session
        self._end_callback = end_callback
        self._violation_count = 0
        self._last_response_at = 0.0
        self._busy = False
        self._room: rtc.Room | None = None

    def attach(self, room: rtc.Room) -> None:
        self._room = room

        @room.on("data_received")
        def _on_data(data: rtc.DataPacket) -> None:
            try:
                msg = json.loads(data.data.decode("utf-8"))
            except Exception:
                return
            if msg.get("type") != "proctor:violation":
                return
            asyncio.create_task(self._handle_violation(msg))

    async def _publish(self, payload: dict) -> None:
        if not self._room:
            return
        data = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        await self._room.local_participant.publish_data(data, reliable=True)

    async def _mute_candidate(self, lock_id: str) -> None:
        await self._publish(
            {"type": "control:mic", "action": "mute", "lock_id": lock_id},
        )

    async def _restore_candidate_mic(self, lock_id: str) -> None:
        await self._publish(
            {"type": "control:mic", "action": "restore", "lock_id": lock_id},
        )

    async def _speak_verbatim(self, text: str) -> None:
        lang_note = (
            "Speak in Vietnamese only."
            if self._language.lower().startswith("vi")
            else "Speak in English only."
        )
        speech = self._agent_session.generate_reply(
            instructions=(
                f"{lang_note} You are the interview proctor. "
                f"Say the following sentence verbatim, word for word, with no additions: {text}"
            ),
        )
        await speech.wait_for_playout()

    async def _handle_violation(self, msg: dict) -> None:
        if self._busy:
            return

        kind = str(msg.get("kind") or "")
        severity = str(msg.get("severity") or "medium")
        if kind == "detection_unsupported" or severity == "info":
            return

        now = time.monotonic()
        cooldown = float(self._settings.proctoring_cooldown_seconds)
        if now - self._last_response_at < cooldown:
            return

        self._busy = True
        lock_id = f"proctor-{uuid.uuid4().hex[:8]}"
        try:
            self._violation_count += 1
            count = self._violation_count
            tier = escalation_tier(count)
            text = warning_text(language=self._language, kind=kind, tier=tier)

            # UI + mic first so the candidate sees/hears the lock before TTS latency.
            await self._publish(
                {
                    "type": "ui:proctor_alert",
                    "kind": kind,
                    "detail": msg.get("detail", ""),
                    "tier": tier,
                    "violation_count": count,
                },
            )
            await self._mute_candidate(lock_id)
            await self._speak_verbatim(text)

            max_v = int(self._settings.proctoring_max_violations)
            if count >= max_v:
                end_text = _ENDING_SCRIPT[_lang_key(self._language)]
                await self._speak_verbatim(end_text)
                await self._publish({"type": "control:end", "reason": "proctoring"})
                await self._end_callback(reason="proctoring", detail=kind)
            else:
                await self._restore_candidate_mic(lock_id)

            self._last_response_at = time.monotonic()
            logger.info(
                "proctor_response interview=%s kind=%s count=%d tier=%d",
                self._interview_id,
                kind,
                count,
                tier,
            )
        except Exception:
            logger.exception("Proctor response failed for %s", self._interview_id)
            try:
                await self._restore_candidate_mic(lock_id)
            except Exception:
                pass
        finally:
            self._busy = False