from app.mcp.assignment_tools import ASSIGNMENT_TOOL_REGISTRY
from app.mcp.interview_tools import INTERVIEW_TOOL_REGISTRY

ALL_TOOLS = {**INTERVIEW_TOOL_REGISTRY, **ASSIGNMENT_TOOL_REGISTRY}
INTERVIEW_TOOLS = INTERVIEW_TOOL_REGISTRY
ASSIGNMENT_TOOLS = ASSIGNMENT_TOOL_REGISTRY

__all__ = ["ALL_TOOLS", "INTERVIEW_TOOLS", "ASSIGNMENT_TOOLS"]